services:
  crafty:
    image: ${CRAFTY_IMAGE:-registry.gitlab.com/crafty-controller/crafty-4:latest}
    container_name: crafty
    restart: unless-stopped
    ports:
      - "${CRAFTY_HTTPS_PORT}:8443"
      - "${CRAFTY_DYNMAP_PORT}:8123"
      - "${CRAFTY_BEDROCK_PORT}:19132/udp"
      - "${CRAFTY_MC_PORT_RANGE}:25500-25600"
    volumes:
      - ${CRAFTY_BACKUPS_PATH}:/crafty/backups
      - ${CRAFTY_LOGS_PATH}:/crafty/logs
      - ${CRAFTY_SERVERS_PATH}:/crafty/servers
      - ${CRAFTY_CONFIG_PATH}:/crafty/app/config
      - ${CRAFTY_IMPORT_PATH}:/crafty/import
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
