services:
  crafty:
    image: ${CRAFTY_IMAGE:-registry.gitlab.com/crafty-controller/crafty-4:latest}
    container_name: crafty
    restart: unless-stopped
    ports:
      - "${CRAFTY_HTTPS_PORT}:8443"
      - "${CRAFTY_MC_PORT_1}:25565/tcp"
      - "${CRAFTY_MC_PORT_1}:25565/udp"
      - "${CRAFTY_MC_PORT_2}:25566/tcp"
      - "${CRAFTY_MC_PORT_2}:25566/udp"
      - "${VOICE_CHAT_PORT}:24454/udp"
    volumes:
      - ${CRAFTY_BACKUPS_PATH}:/crafty/backups
      - ${CRAFTY_LOGS_PATH}:/crafty/logs
      - ${CRAFTY_SERVERS_PATH}:/crafty/servers
      - ${CRAFTY_CONFIG_PATH}:/crafty/app/config
      - ${CRAFTY_IMPORT_PATH}:/crafty/import
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
