services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.15.0
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ${NPM_DATA_PATH}:/data
      - ${NPM_LETSENCRYPT_PATH}:/etc/letsencrypt
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
