- name: Startpage
  width: slim
  hide-desktop-navigation: true
  center-vertically: true
  columns:
    - size: full
      widgets:
        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Miniflux
              url: http://miniflux.lab.tencorvids.com
              icon: sh:miniflux
            - title: Immich
              url: http://immich.lab.tencorvids.com
              icon: sh:immich
            - title: Jellyfin
              url: http://jellyfin.lab.tencorvids.com
              icon: sh:jellyfin
            - title: Seerr
              url: http://seerr.lab.tencorvids.com
              icon: sh:seerr

        - type: monitor
          cache: 1m
          title: Torrent
          sites:
            - title: qBittorrent 
              url: http://qbittorrent.lab.tencorvids.com
              icon: sh:qbittorrent
            - title: NZBGet
              url: http://nzbget.lab.tencorvids.com
              icon: sh:nzbget
              alt-status-codes: [200, 401]
            - title: Prowlarr
              url: http://prowlarr.lab.tencorvids.com
              icon: sh:prowlarr
            - title: Sonarr
              url: http://sonarr.lab.tencorvids.com
              icon: sh:sonarr
            - title: Radarr
              url: http://radarr.lab.tencorvids.com
              icon: sh:radarr
            - title: Profilarr
              url: http://profilarr.lab.tencorvids.com
              icon: sh:profilarr

        - type: monitor
          cache: 1m
          title: Core
          sites:
            - title: "Proxmox Node 1"
              url: https://pve1.lab.tencorvids.com
              icon: sh:proxmox
            - title: "Proxmox Node 2"
              url: https://pve2.lab.tencorvids.com
              icon: sh:proxmox
            - title: "Proxmox Node 3"
              url: https://pve3.lab.tencorvids.com
              icon: sh:proxmox
            - title: Unifi
              url: https://unifi.ui.com/consoles/6C63F8AC21BB00000000093C55AC0000000009BB92EF00000000685BD4CE:888987432/network/default/dashboard
              icon: sh:ubiquiti-unifi
            - title: TrueNAS
              url: http://nas.lab.tencorvids.com
              icon: sh:truenas-core
            - title: Ship
              url: http://ship.lab.tencorvids.com
              icon: sh:komodo
            - title: NGINX Proxy Manager
              url: http://proxy.lab.tencorvids.com
              icon: sh:nginx

        - type: monitor
          cache: 1m
          title: DMZ
          sites:
            - title: Buoy
              url: http://buoy.lab.tencorvids.com
              icon: sh:komodo
            - title: Crafty
              url: http://crafty.lab.tencorvids.com
              icon: sh:minecraft

